change-id = 125535

[llvm]
download-ci-llvm = true
#download-ci-llvm = false
#targets = "AArch64;X86;WebAssembly"
#experimental-targets = ""
#version-suffix = "-dusk"

[build]
target = ["wasm32-unknown-unknown", "wasm64-unknown-unknown"]
docs = false
extended = true

[rust]
channel = "nightly"
description = "Dusk Network's Smart Contract Compiler"

[dist]
compression-formats = ["gz"]
compression-profile = "best"
