change-id = 125535

[llvm]
download-ci-llvm = true
#download-ci-llvm = false
#targets = "AArch64;X86;WebAssembly"
#experimental-targets = ""
#version-suffix = "-dusk"

[build]
target = ["wasm32-unknown-unknown", "wasm64-unknown-unknown"]
docs = false
extended = true

[rust]
channel = "nightly"
description = "Dusk Network's Smart Contract Compiler"

[dist]
compression-formats = ["gz"]
compression-profile = "best"

[target.x86_64-unknown-linux-gnu]
llvm-config = "/usr/lib/llvm-14/bin/llvm-config"

[target.x86_64-apple-darwin]
llvm-config = "/usr/local/opt/llvm/bin/llvm-config"

[target.aarch64-apple-darwin]
llvm-config = "/opt/homebrew/opt/llvm/bin/llvm-config"

